### ISSUE TITLE
Doesn't work on Ubuntu 24.04 

### ISSUE THREAD

**Issue by DizkiBorsuk** [unobserved-io/Furtherance#162]
Hi, 
Both .deb and flatpack version doesn't even start on Ubuntu 24.04. Deb version tries to open window but it fails and flatpack version doesn't do anything. 
I used to use furtherance on ubuntu 22 a lot so i hope this issue can be solved. Thanks a lot.

**Comment by DizkiBorsuk** [comment]
Sure, for .deb version: 
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/window.rs:1140:41:
Failed to call XMapRaised: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/window.rs:581:34:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x5de02c9d5d89 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h5b6bd5631a6d1f6b
   1:     0x5de02c017163 - core::fmt::write::h7550c97b06c86515
   2:     0x5de02c99f8d2 - std::io::Write::write_fmt::h7b09c64fe0be9c84
   3:     0x5de02c9dab22 - std::sys::backtrace::BacktraceLock::print::h2395ccd2c84ba3aa
   4:     0x5de02c9da98b - std::panicking::default_hook::{{closure}}::he19d4c7230e07961
   5:     0x5de02c9db046 - std::panicking::rust_panic_with_hook::h8942133a8b252070
   6:     0x5de02c9dabf8 - std::panicking::begin_panic_handler::{{closure}}::hb5f5963570096b29
   7:     0x5de02c9dab59 - std::sys::backtrace::__rust_end_short_backtrace::h6208cedc1922feda
   8:     0x5de02c9dab4c - rust_begin_unwind
   9:     0x5de02be967cf - core::panicking::panic_fmt::h0c3082644d1bf418
  10:     0x5de02be96ba5 - core::result::unwrap_failed::hd20b4aa073bda1e2
  11:     0x5de02cd943bf - winit::platform_impl::linux::x11::window::UnownedWindow::shared_state_lock::ha1e17a16858f70c0
  12:     0x5de02cdc33e0 - <winit::window::Window as core::ops::drop::Drop>::drop::h611ee13abcbe23df
  13:     0x5de02c351c93 - alloc::sync::Arc<T,A>::drop_slow::h7a61bae8b94e3133
  14:     0x5de02c1229d4 - core::ptr::drop_in_place<wgpu::Surface>::h059eddd2cacb7be5
  15:     0x5de02c12414f - core::ptr::drop_in_place<iced_winit::program::window_manager::Window<iced::program::Program::run_with::Instance<iced::program::with_theme::WithTheme<iced::program::with_subscription::WithSubscription<iced::program::with_title::WithTitle<iced::application::application::Instance<furtherance::app::Furtherance,furtherance::app::Message,iced_core::theme::Theme,iced_renderer::fallback::Renderer<iced_wgpu::Renderer,iced_tiny_skia::Renderer>,furtherance::app::Furtherance::update,furtherance::app::Furtherance::view>,iced::application::Application<iced::application::application::Instance<furtherance::app::Furtherance,furtherance::app::Message,iced_core::theme::Theme,iced_renderer::fallback::Renderer<iced_wgpu::Renderer,iced_tiny_skia::Renderer>,furtherance::app::Furtherance::update,furtherance::app::Furtherance::view>>::title<furtherance::app::Furtherance::title>::{{closure}}>,furtherance::app::Furtherance::subscription>,iced::application::Application<iced::program::with_subscription::WithSubscription<iced::program::with_title::WithTitle<iced::application::application::Instance<furtherance::app::Furtherance,furtherance::app::Message,iced_core::theme::Theme,iced_renderer::fallback::Renderer<iced_wgpu::Renderer,iced_tiny_skia::Renderer>,furtherance::app::Furtherance::update,furtherance::app::Furtherance::view>,iced::application::Application<iced::application::application::Instance<furtherance::app::Furtherance,furtherance::app::Message,iced_core::theme::Theme,iced_renderer::fallback::Renderer<iced_wgpu::Renderer,iced_tiny_skia::Renderer>,furtherance::app::Furtherance::update,furtherance::app::Furtherance::view>>::title<furtherance::app::Furtherance::title>::{{closure}}>,furtherance::app::Furtherance::subscription>>::theme<furtherance::app::Furtherance::theme>::{{closure}}>,furtherance::app::Furtherance::new>,iced_renderer::fallback::Compositor<iced_wgpu::window::compositor::Compositor,iced_tiny_skia::window::compositor::Compositor>>>::hc318bbfb9a67826a.9661
  16:     0x5de02bf26276 - core::ptr::drop_in_place<iced_winit::program::window_manager::WindowManager<iced::program::Program::run_with::Instance<iced::program::with_theme::WithTheme<iced::program::with_subscription::WithSubscription<iced::program::with_title::WithTitle<iced::application::application::Instance<furtherance::app::Furtherance,furtherance::app::Message,iced_core::theme::Theme,iced_renderer::fallback::Renderer<iced_wgpu::Renderer,iced_tiny_skia::Renderer>,furtherance::app::Furtherance::update,furtherance::app::Furtherance::view>,iced::application::Application<iced::application::application::Instance<furtherance::app::Furtherance,furtherance::app::Message,iced_core::theme::Theme,iced_renderer::fallback::Renderer<iced_wgpu::Renderer,iced_tiny_skia::Renderer>,furtherance::app::Furtherance::update,furtherance::app::Furtherance::view>>::title<furtherance::app::Furtherance::title>::{{closure}}>,furtherance::app::Furtherance::subscription>,iced::application::Application<iced::program::with_subscription::WithSubscription<iced::program::with_title::WithTitle<iced::application::application::Instance<furtherance::app::Furtherance,furtherance::app::Message,iced_core::theme::Theme,iced_renderer::fallback::Renderer<iced_wgpu::Renderer,iced_tiny_skia::Renderer>,furtherance::app::Furtherance::update,furtherance::app::Furtherance::view>,iced::application::Application<iced::application::application::Instance<furtherance::app::Furtherance,furtherance::app::Message,iced_core::theme::Theme,iced_renderer::fallback::Renderer<iced_wgpu::Renderer,iced_tiny_skia::Renderer>,furtherance::app::Furtherance::update,furtherance::app::Furtherance::view>>::title<furtherance::app::Furtherance::title>::{{closure}}>,furtherance::app::Furtherance::subscription>>::theme<furtherance::app::Furtherance::theme>::{{closure}}>,furtherance::app::Furtherance::new>,iced_renderer::fallback::Compositor<iced_wgpu::window::compositor::Compositor,iced_tiny_skia::window::compositor::Compositor>>>::h602320f0b1231897
  17:     0x5de02bf080c2 - iced_winit::program::run_instance::{{closure}}::h47faf4eb3cce4d36
  18:     0x5de02bf0bc6b - iced_winit::program::run::Runner<Message,F,C>::process_event::h497f6ad4476552dc
  19:     0x5de02bf0c8fa - iced_winit::program::run::Runner<Message,F,C>::process_event::h497f6ad4476552dc
  20:     0x5de02c28d690 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::he5685f6fcbe9224e
  21:     0x5de02c2cd010 - winit::platform_impl::linux::x11::EventLoop<T>::run_on_demand::hbfc9531db618dcf7
  22:     0x5de02bf0aaee - iced_winit::program::run::hbf0840db7731bddb
  23:     0x5de02c308288 - furtherance::main::h7de3ca9e6eebbe3a
  24:     0x5de02c285bc3 - std::sys::backtrace::__rust_begin_short_backtrace::haeb951e74dfb4e81
  25:     0x5de02c3076ed - main
  26:     0x7ff94ec2a1ca - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  27:     0x7ff94ec2a28b - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  28:     0x5de02befb175 - _start
  29:                0x0 - <unknown>
thread 'main' panicked at core/src/panicking.rs:229:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
Aborted (core dumped)

**Comment by rickykresslein** [comment]
I setup a completely fresh install Ubuntu 24.04 to test this and tried both the flatpak and deb on both x11 and wayland, and all 4 trials worked without any issue. I'm not sure what is going on with your system. My guess would be a dependency is missing, but that shouldn't make a difference for the Flatpak. 

You could try these steps:

1. Try it in Wayland
2. Try to install these dependencies
`sudo apt install libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libpango1.0-dev`
3. Run it with `WINIT_UNIX_BACKEND=x11 furtherance` (if still on x11)
4. Download the source code and run it with `cargo run` and see if it runs that way. (you may need to install other dependencies for this)

**Comment by DizkiBorsuk** [comment]
Thanks, it works just fine on wayland, on x11 even after 2 and 3 it doesn't but i'm fine with just switching to wayland. The only reason i can think of is that i have nvidia gpu, os itself is rather normal, fresh ubuntu with snap removed. Thanks for help.

**Comment by rickykresslein** [comment]
Okay, cool. I will keep trying to reproduce the error and see if I can figure it out, because it should definitely work on x11 too. Glad it works on Wayland though!
